### ISSUE TITLE
Heroku - worker support

### ISSUE THREAD

**Issue by andreasklinger** [fgrehm/letter_opener_web#35]
Hi guys

It seems letter_opener_web won't be much of use on heroku. I would assume that most people use workers to send their emails.

As far as i understand [this](http://stackoverflow.com/questions/23859462/heroku-file-storage-with-sidekiq) workers and all dynos have [isolated](https://devcenter.heroku.com/articles/dynos#isolation-and-security) environments. Thus it can't really reach the same `/tmp` directory.

Thinking about it makes as a lot of sense.
A workaround would be s3 support i guess. Unfortunately i personally can't implement that right now. But i think it would be worth the note in the README that it only works on heroku under certain conditions. Simply to save the time of the next person ;)

best wishes
Andreas

**Comment by pseudomuto** [comment]
The resolution for now seems to be the notice in the README. Since this is a few years old, I'm going to close it. If this is still a concern, re-open.

**Comment by NullVoxPopuli** [comment]
what if there was an option to store emails in redis?

**Comment by fgrehm** [comment]
That or storing it on the DB would also work

**Comment by kreintjes** [comment]
Still a concern for me. Could use this for Heroku when sending mails with deliver_later. However, if I'm the only one, it might not be worth the trouble :p

Any suggestions on how to test (mass) mails in staging environments on Heroku without sending them to real people?

**Comment by eliotsykes** [comment]
There's a Heroku add-on that does this, there may be others: https://elements.heroku.com/addons/mailtrap

**Comment by pdabrowski6** [comment]
If anyone has troubles with using this gem on Heroku with multiple workers, I solved this issue with this PR: https://github.com/fgrehm/letter_opener_web/pull/129

If the PR is not merged, you can use the updated version the following way:

```
gem 'letter_opener_web', git: 'https://github.com/pdabrowski6/letter_opener_web', branch: 'support-for-s3'
```

**Comment by gamesover** [comment]
> If anyone has troubles with using this gem on Heroku with multiple workers, I solved this issue with this PR: #129
> 
> If the PR is not merged, you can use the updated version the following way:
> 
> ```
> gem 'letter_opener_web', git: 'https://github.com/pdabrowski6/letter_opener_web', branch: 'support-for-s3'
> ```

A brilliant solution for AWS S3 users. However, it's still not a universal solution for those who run Rails server and background servers (such as Sidekiq) separately.

**Comment by coorasse** [comment]
We could persist the letters in a database table. This would be an interesting approach nowadays. I'll open a issue on letter_opener itself to see if it could be interesting

**Comment by mddelk** [comment]
https://github.com/coorasse/letter_thief

**Comment by gamesover** [comment]
> https://github.com/coorasse/letter_thief

This gem has two heavy requirements:

1. It requires a database migration and schema changes.
2. It depends on Active Storage, which not every Old Rails project uses.

I’d prefer @pdabrowski6  PR to only rely on S3.
