### ISSUE TITLE
html / plain text views

### ISSUE THREAD

**Issue by bergerjac** [fgrehm/letter_opener_web#39]
any thoughts on adding a radio toggle `[html] | [text]` similar to [letter_opener](https://github.com/ryanb/letter_opener/blob/v1.3.0/lib/letter_opener/message.html.erb#L113)

if so, I'd think to the left or right of the _headers_ area

default to `[html]`, (not sure about desired persistency behavior when navigating from one mail to the next)

**Comment by fgrehm** [comment]
If the mailer has a `text` format, things should work out just fine. There is a link at the top right corner of the email view:

![image](https://cloud.githubusercontent.com/assets/81859/6547695/56beb480-c5be-11e4-9a55-ce1194d3c58f.png)

Which links to the plain text version of the email that went out:

![image](https://cloud.githubusercontent.com/assets/81859/6547696/5f72120c-c5be-11e4-84fa-10c23ced4ddd.png)

HTH
