### ISSUE TITLE
Eliminate need to require the gem in every environment

### ISSUE THREAD

**Issue by schnittchen** [fgrehm/letter_opener_web#48]
The way the gem initialization works, it is not possible to write

```
gem 'letter_opener_web', require: false
```

and adding

```
require 'letter_opener_web'
```

at the top of the desired environment configuration file(s).

This means letter_opener_web is loaded (and the delivery method registered etc.) in production where I certainly do not need it.

**Comment by Startouf** [comment]
Adding the gem to your development group does work. Just make sure your config/routes never come across some code that needs this library in other environments.

```
group :development do
  gem 'letter_opener_web'
end
```

**Comment by pseudomuto** [comment]
Seems like @Startouf's comment resolves this. Feel free to re-open is this is still a concern
