### ISSUE TITLE
Rails 5 deprecation warning

### ISSUE THREAD

**Issue by connorshea** [fgrehm/letter_opener_web#50]
I've been testing GitLab with Rails 5, and ran into this deprecation warning when I went to our Letter Opener route:

```
Started GET "/rails/letter_opener/1468524894_56e3355/rich" for 127.0.0.1 at 2016-07-27 14:05:57 -0600
Processing by LetterOpenerWeb::LettersController#show as HTML
  Parameters: {"id"=>"1468524894_56e3355", "style"=>"rich"}
DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is `text/plain`.
```

Context of deprecating this:
- https://github.com/rails/rails/commit/4b3f8acce284d1f1721080d08222a7dd79ca69f5
- https://github.com/rails/rails/issues/12374

I can provide an example app if you'd like me to.

**Comment by harigopal** [comment]
Related to above, there are deprecation warnings on boot:

```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1.
Use before_action instead. (called from <class:LettersController> at
.../letter_opener_web-1.3.0/app/controllers/letter_opener_web/letters_controller.rb:5)
```

These being the culprit:

https://github.com/fgrehm/letter_opener_web/blob/master/app/controllers/letter_opener_web/letters_controller.rb#L5-L6

**Comment by josisusan** [comment]
The fix can be found on https://github.com/fgrehm/letter_opener_web/pull/54

**Comment by pseudomuto** [comment]
This is resolved on master
