### ISSUE TITLE
Change location

### ISSUE THREAD

**Issue by nicolas-besnard** [fgrehm/letter_opener_web#57]
I'd like to change the default location `Rails.root.join('tmp', 'letter_opener')` by a custom one.

Is there any way to achieve that ? I've seed that the location is also present in LetterOpenerWeb::Letter.letters_location

**Comment by pseudomuto** [comment]
Have you tired setting `LetterOpenerWeb:Letter.letters_location` to another path in development.rb?

**Comment by josisusan** [comment]
We had to change the location on:
```
# lib/letter_opener_web/engine.rb
ActionMailer::Base.add_delivery_method :letter_opener_web, LetterOpenerWeb::DeliveryMethod, :location => ...
```
as well
