### ISSUE TITLE
Release v1.3.1

### ISSUE THREAD

**Issue by pseudomuto** [fgrehm/letter_opener_web#62]
Hey @fgrehm, you mentioned I should ping you when I was ready to cut a new release. In an effort to get the rails 5 stuff out, I want to make a 1.3.1 release using 78f81e08fad4fe6497f04ac5b829acc88cb68250.

Would you be able to give me push access to rubygems?

**Comment by fgrehm** [comment]
Hey @pseudomuto, great work and tks for keeping the fire burning! is the email address on your GH profile the same u have registered on rubygems?

**Comment by pseudomuto** [comment]
Yep! That's the one!

**Comment by pseudomuto** [comment]
ping @fgrehm

**Comment by fgrehm** [comment]
Done! Please make sure the CHANGELOG is up to date and / or you add some release notes after cutting the release. Tks a lot and LMK if you need any additional help or another set of 👀 in a future PR!

**Comment by pseudomuto** [comment]
Will do! Thanks man!

**Comment by pseudomuto** [comment]
And done!

https://github.com/fgrehm/letter_opener_web/compare/v1.3.0...v1.3.1
