### ISSUE TITLE
Execution of ApplicationController filters

### ISSUE THREAD

**Issue by maurosbu** [fgrehm/letter_opener_web#76]
I have a problem with version 1.3.2.
The filters defined in ApplicationController of my application (*app/controllers/application_controller.rb*) are executed when accessising the list of emails.

This is strange beacuse LettersController ([app/controllers/letter_opener_web/letters_controller.rb](https://github.com/fgrehm/letter_opener_web/blob/master/app/controllers/letter_opener_web/letters_controller.rb)) inherits from ApplicationController defined within the gem ([app/controllers/letter_opener_web/application_controller.rb](https://github.com/fgrehm/letter_opener_web/blob/master/app/controllers/letter_opener_web/application_controller.rb)).

Any idea on how to solve this issue?

Many thanks in advance.

**Comment by ciihla** [comment]
You can skip filters in ApplicationController `if defined?(LetterOpenerWeb::LettersController) && is_a?(LetterOpenerWeb::LettersController)`
Or fork the gen end extend `class LettersController < LetterOpenerWeb::ApplicationController`
That should solve your problem..

**Comment by maurosbu** [comment]
@ciihla at the moment I skip filters using an initializer with the following code:
    
    Rails.application.config.to_prepare do
        LetterOpenerWeb::LettersController.skip_before_action :filter1, :filter2
    end

It could be useful to let the developer choose the behaviour through a **letter_opener_web** config parameter. This way one may choose between extending own application controller or not.

What do you think?

Mauro

**Comment by pseudomuto** [comment]
Sorry for the delay everyone...please feel free to ping me in PRs and issues in the future so I get notified.

**Comment by pseudomuto** [comment]
Resolved by #82
