### ISSUE TITLE
SystemStackError occures when more than 30 messages.

### ISSUE THREAD

**Issue by ikuhanarock** [fgrehm/letter_opener_web#86]
I have a problem with `SystemStackError` occures.

```
SystemStackError - stack level too deep:
```

Reproduction method:
1. more than 30 messages in `/inbox`.
1. access to `/inbox` page.
 
Environment:
Ruby v2.5.1
Rails v5.1.4
letter_opener_web v1.3.4

**Comment by fgrehm** [comment]
Sorry for the long delay here but are you able to reproduce this with the latest release of this gem and Rails? I've just tested on Rails 6, letter_opener_web 1.4.0 and Ruby 2.6.5.

I was able to load the UI with 57 messages:

![image](https://user-images.githubusercontent.com/81859/74698521-dff12800-51dc-11ea-9fe4-bccb33406085.png)

**Comment by fgrehm** [comment]
Hey @ikuhanarock I'm doing some cleaning of issues and PRs in prep for a 2.0 release. If by any chance this is still a problem for you in the latest 1.x release please open a new issue.

Sorry for the long delay here!
