### ISSUE TITLE
Rails 6.0 is out

### ISSUE THREAD

**Issue by jlecour** [fgrehm/letter_opener_web#97]
Hi folks,

It look like Rails 6.0 is finally out but `letter_opener_web` requires an older version of `railties`.

Thanks a lot to anyone who can help on this.

**Comment by fgrehm** [comment]
I've just tested it on a Rails 6.0 app and it werks!

TBH, we've never locked the gem to a specific railties release, we've had the line below for [more than 5 years](https://github.com/fgrehm/letter_opener_web/commit/5f337eb0c7806eb166b45952870da53d586f9db1) :sweat_smile: 

https://github.com/fgrehm/letter_opener_web/blob/9664fbf9bf07d5edeb5acb2f057c0caf572b5ebe/letter_opener_web.gemspec#L22

Please open a separate issue if you are having trouble with Rails 6.0, I've been missing in action for a while but @pseudomuto has been doing a great job on keeping this project running
